import { expect, test } from "@playwright/test";
import { command, createSimpleTournament, login, openMatchFromCard, publishNext, snapshot } from "../../support/swiss20-browser";

test("WORKFLOW-A: clock layout, blocked-tab retry and score drafts survive reopening", async ({ page }) => {
  await login(page);
  const id = await createSimpleTournament(page, "Device workflow recovery", "Alex Rowan\nMorgan Vale", 1);
  const current = await publishNext(page, id, 1);
  const match = current.rounds[0].matches[0];
  await openMatchFromCard(page, id, match.id);
  const firstSide = await page.locator("[data-side]").first().getAttribute("data-side");
  await page.getByRole("button", { name: "Flip sides", exact: true }).click();
  await page.reload();
  await expect(page.getByRole("button", { name: "Start Timer", exact: true })).toBeEnabled();
  await expect(page.locator("[data-side]").first()).not.toHaveAttribute("data-side", firstSide!);
  const second = await page.context().newPage();
  await second.goto(`/match/${match.id}`);
  await expect(second.getByRole("button", { name: "Try controlling on this tab", exact: true })).toBeVisible();
  await page.goto(`/t/${id}`);
  await second.getByRole("button", { name: "Try controlling on this tab", exact: true }).click();
  await expect(second.getByRole("button", { name: "Start Timer", exact: true })).toBeEnabled();
  await second.getByRole("button", { name: "Start Timer", exact: true }).click();
  await second.getByRole("button", { name: "End game", exact: true }).click();
  const scores = second.locator('input[aria-label$="game score"]');
  await scores.nth(0).fill("401"); await scores.nth(1).fill("399");
  await expect.poll(() => second.evaluate(() => Object.keys(localStorage).some(key => key.startsWith("crossplay.report-draft.")))).toBe(true);
  await second.reload();
  await second.getByRole("button", { name: "Restore draft", exact: true }).click();
  await expect(scores.nth(0)).toHaveValue("401"); await expect(scores.nth(1)).toHaveValue("399");
  await second.getByRole("button", { name: "Review scores", exact: true }).click();
  await second.getByRole("button", { name: /: agree$/ }).first().click();
  await expect(second.getByRole("button", { name: /: agree$/ })).toHaveCount(1);
  await second.getByRole("button", { name: /: agree$/ }).click();
  await expect(second.getByRole("heading", { name: "Match complete", exact: true })).toBeVisible();
  expect((await snapshot(second.request, id)).rounds[0].matches[0].result).toMatchObject({ raw1: 401, raw2: 399 });
  await second.close();
});

test("WORKFLOW-A: departure retains rank and history and excludes later pairings", async ({ page }) => {
  await login(page);
  const id = await createSimpleTournament(page, "Departed player standings", "Alex Rowan\nMorgan Vale\nCasey Finch\nJamie Reed", 2, 2, 10, null);
  let current = await publishNext(page, id, 1);
  for (const match of current.rounds[0].matches) expect((await command(page.request, id, "finalize_result", { matchId: match.id, expectedRevision: match.revision, kind: "played", raw1: 401, raw2: 399, overtime1: 0, overtime2: 0 })).ok()).toBe(true);
  current = await snapshot(page.request, id);
  const departed = current.rounds[0].matches[0].player1Id;
  const before = current.standings.find(row => row.entrantId === departed)!;
  const history = current.rounds[0].matches;
  await page.goto(`/admin/tournaments/${id}/players`);
  const name = current.entrants.find(entrant => entrant.id === departed)!.name;
  await page.locator(".roster-row").filter({ hasText: name }).getByRole("button", { name: "Remove from future rounds", exact: true }).click();
  await expect(page.locator(".roster-row").filter({ hasText: name })).toContainText("results and final ranking remain");
  current = await publishNext(page, id, 2);
  expect(current.rounds[1].matches.flatMap(match => [match.player1Id, match.player2Id])).not.toContain(departed);
  for (const match of current.rounds[1].matches.filter(match => match.player2Id)) expect((await command(page.request, id, "finalize_result", { matchId: match.id, expectedRevision: match.revision, kind: "played", raw1: 390, raw2: 390, overtime1: 0, overtime2: 0 })).ok()).toBe(true);
  expect((await command(page.request, id, "finish_tournament", { reason: "" })).ok()).toBe(true);
  current = await snapshot(page.request, id);
  expect(current.rounds[0].matches).toEqual(history);
  expect(current.standings.find(row => row.entrantId === departed)).toMatchObject({ active: false, matchPoints: before.matchPoints, difference: before.difference, wins: before.wins });
  await page.goto(`/t/${id}`);
  await expect(page.getByRole("heading", { name: "Final standings", exact: true })).toBeVisible();
  await expect(page.locator("#standings tbody tr")).toHaveCount(4);
  await page.goto(`/t/${id}/players/${departed}`);
  await expect(page.getByRole("article")).toHaveCount(1);
});
