import { expect, test, type Page } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { baseURL, command, createSimpleTournament, evidencePath, fillScore, login, publishNext, snapshot, writeEvidence } from "../../support/swiss20-browser";
import type { MatchClockSnapshot } from "../../../src/client/match-clock-api";

async function capture(page: Page, name: string, project: string) {
  const original = page.viewportSize();
  for (const [device, width, height] of [["mobile", 390, 844], ["ipad", 820, 1180]] as const) {
    await page.setViewportSize({ width, height });
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `${name} fits ${device}`).toBe(true);
    await page.screenshot({ path: evidencePath("screens", project, `${name}-${device}.png`), fullPage: true, animations: "disabled" });
  }
  if (original) await page.setViewportSize(original);
}
async function readClock(page: Page, id: string) { return (await page.request.get(`${baseURL}/api/matches/${id}/clock`)).json() as Promise<MatchClockSnapshot>; }

test("TABLES: remembered duty, shared replacement, receipts, closure, departure and next round", async ({ page, browser }, info) => {
  await login(page);
  const id = await createSimpleTournament(page, "Autumn Crossplay", "Alex Rowan\nMorgan Vale\nCasey Finch\nJamie Reed\nSam Rivera\nRobin Park", 2);
  await capture(page, "01-roster-next-step", info.project.name);
  await page.goto(`/admin/tournaments/${id}/settings`);
  await page.getByRole("button", { name: "Save settings", exact: true }).click();
  await capture(page, "02-settings-next-step", info.project.name);
  await page.goto(`/admin/tournaments/${id}/tables`);
  await page.getByLabel("Table numbers", { exact: true }).fill("1, 2");
  await capture(page, "03-table-setup", info.project.name);
  await page.getByRole("button", { name: "Enable table management", exact: true }).click();
  await page.getByLabel("Device name", { exact: true }).fill("Front iPad");
  await page.getByRole("button", { name: "Use this device at Table 1", exact: true }).click();
  await expect(page.getByText("This device serves Table 1.", { exact: false })).toBeVisible();
  await page.goto(`/t/${id}/table`);
  await capture(page, "04-assigned-waiting", info.project.name);
  let current = await publishNext(page, id, 1);
  expect(current.tables?.locations.filter(location => location.ready)).toHaveLength(2);
  const first = current.rounds[0].matches.find(match => current.tables?.locations.find(location => location.matchId === match.id)?.tableNumber === 1)!;
  const pairs = current.rounds[0].matches.map(match => [match.id, match.player1Id, match.player2Id]);
  await page.goto(`/t/${id}`);
  await expect(page).toHaveURL(/\/table$/);
  await capture(page, "05-my-table-and-queue", info.project.name);
  await page.getByRole("link", { name: "Browse all tables", exact: true }).click();
  await page.getByLabel("Table", { exact: true }).selectOption("2");
  await capture(page, "06-temporary-browsing", info.project.name);
  await page.getByRole("link", { name: "My table", exact: true }).first().click();
  await expect(page.getByRole("heading", { name: "Table 1", exact: true })).toBeVisible();
  await page.reload();
  await page.locator(`#match-${first.id}`).getByRole("button", { name: "Start Match", exact: true }).click();
  await expect(page.getByRole("button", { name: "Start Timer", exact: true })).toBeEnabled();
  await capture(page, "07-remembered-clock-layout", info.project.name);
  await page.getByRole("button", { name: "Start Timer", exact: true }).click();
  await page.getByRole("button", { name: "Pause", exact: true }).click();
  await expect.poll(async () => (await readClock(page, first.id)).state?.status).toBe("paused");
  const saved = await readClock(page, first.id);
  await capture(page, "08-paused-for-handoff", info.project.name);
  const secondContext = await browser.newContext({ baseURL, viewport: { width: 390, height: 844 } });
  const second = await secondContext.newPage();
  await login(second);
  await second.goto(`/admin/tournaments/${id}/tables`);
  await second.getByLabel("Device name", { exact: true }).fill("Replacement phone");
  await second.getByLabel("Assign to table", { exact: true }).selectOption("2");
  await second.getByRole("button", { name: "Use this device at Table 2", exact: true }).click();
  const table1 = second.getByRole("article", { name: "Manage Table 1", exact: true });
  await table1.getByText("Replace or release this match’s device", { exact: true }).click();
  await table1.getByLabel("Reason for changing device", { exact: true }).fill("Front iPad needs to leave the event");
  await capture(second, "09-replace-device", info.project.name);
  await table1.getByRole("button", { name: "Replace this table’s device with this device", exact: true }).click();
  await expect(table1.getByText("This device now controls the match.", { exact: false })).toBeVisible();
  expect((await readClock(second, first.id)).state?.usedMs).toEqual(saved.state?.usedMs);
  await expect(second.getByLabel("Assign to table", { exact: true })).toHaveValue("1");
  await expect(second.getByText("This device is assigned to Table 2.", { exact: true })).toHaveCount(0);
  await capture(second, "10-review-saved-time", info.project.name);
  await table1.getByLabel("Reason", { exact: true }).fill("Verified saved pause with both players");
  await table1.getByRole("button", { name: "Save record", exact: true }).click();
  await expect(table1.getByText("Saved.", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("button", { name: "Resume", exact: true })).toBeDisabled();
  const noLongerControlled = await readClock(page, first.id);
  expect(noLongerControlled.canControl).toBe(false);
  await table1.getByRole("link", { name: "Continue to match", exact: true }).click();
  await expect(second.getByRole("button", { name: "Resume", exact: true })).toBeEnabled();
  await second.getByRole("button", { name: "End game", exact: true }).click();
  const scores = second.locator('input[aria-label$="game score"]');
  await scores.nth(0).fill("401"); await scores.nth(1).fill("399");
  await capture(second, "11-score-entry", info.project.name);
  await second.reload();
  await second.getByRole("button", { name: "Restore draft", exact: true }).click();
  await expect(scores.nth(0)).toHaveValue("401");
  await second.getByRole("button", { name: "Review scores", exact: true }).click();
  await second.getByRole("button", { name: /: agree$/ }).first().click();
  await expect(second.getByRole("button", { name: /: agree$/ })).toHaveCount(1);
  await capture(second, "12-pending-confirmation", info.project.name);
  await second.getByRole("button", { name: /: agree$/ }).click();
  await expect(second).toHaveURL(/\/table$/);
  await expect(second.getByRole("heading", { name: "Result saved · Round 1", exact: true })).toBeVisible();
  await capture(second, "13-result-receipt-next-match", info.project.name);
  await second.goto(`/admin/tournaments/${id}/tables`);
  const table2 = second.getByRole("article", { name: "Manage Table 2", exact: true });
  await table2.getByText("Move matches or close table", { exact: true }).click();
  await table2.getByLabel("Reason for moving", { exact: true }).fill("One device remains at the event");
  await capture(second, "14-close-table-summary", info.project.name);
  await table2.getByRole("button", { name: "Confirm move and close table", exact: true }).click();
  await expect(table2.getByText("Closed", { exact: true })).toBeVisible();
  await capture(second, "15-managed-tables", info.project.name);
  current = await snapshot(second.request, id);
  expect(current.rounds[0].matches.map(match => [match.id, match.player1Id, match.player2Id])).toEqual(pairs);
  expect(current.tables?.locations.find(location => location.matchId === first.id)?.tableNumber).toBe(1);
  const remaining = current.rounds[0].matches.filter(match => match.status !== "final");
  const queued = remaining.find(match => !current.tables?.locations.find(location => location.matchId === match.id)?.ready)!;
  const deviceId = await second.evaluate(() => localStorage.getItem("crossplay.device-id"));
  const staleLink = await second.request.post(`${baseURL}/api/matches/${queued.id}/open`, { headers: { Origin: baseURL }, data: { requestId: randomUUID(), controllerId: randomUUID(), deviceId, expectedOperationsVersion: current.tables?.version } });
  expect(staleLink.status()).toBe(409);
  expect((await staleLink.json()).code).toBe("TABLE_NOT_READY");
  for (const match of remaining) expect((await command(second.request, id, "finalize_result", { matchId: match.id, expectedRevision: match.revision, kind: "played", raw1: 401, raw2: 399, overtime1: 0, overtime2: 0, reason: "Verified scores at the table" })).ok()).toBe(true);
  const departed = first.player1Id, name = current.entrants.find(entrant => entrant.id === departed)!.name;
  await second.goto(`/admin/tournaments/${id}/players`);
  await second.locator(".roster-row").filter({ hasText: name }).getByRole("button", { name: "Remove from future rounds", exact: true }).click();
  await expect(second.locator(".roster-row").filter({ hasText: name })).toContainText("Withdrawn");
  await capture(second, "16-departure-keeps-results", info.project.name);
  const history = (await snapshot(second.request, id)).rounds[0].matches;
  current = await publishNext(second, id, 2);
  expect(current.rounds[1].matches.flatMap(match => [match.player1Id, match.player2Id])).not.toContain(departed);
  expect(current.tables?.locations.filter(location => current.rounds[1].matches.some(match => match.id === location.matchId)).every(location => location.tableNumber === 1)).toBe(true);
  await second.getByLabel("Show matches", { exact: true }).selectOption("unresolved");
  await capture(second, "17-organizer-work-queue", info.project.name);
  await second.goto(`/t/${id}/table`);
  await capture(second, "18-next-round-at-my-table", info.project.name);
  for (const match of current.rounds[1].matches.filter(match => match.player2Id)) expect((await command(second.request, id, "finalize_result", { matchId: match.id, expectedRevision: match.revision, kind: "played", raw1: 390, raw2: 390, overtime1: 0, overtime2: 0, reason: "Verified round two scores" })).ok()).toBe(true);
  expect((await command(second.request, id, "finish_tournament", { reason: "" })).ok()).toBe(true);
  current = await snapshot(second.request, id);
  expect(current.rounds[0].matches).toEqual(history);
  expect(current.standings.find(row => row.entrantId === departed)).toMatchObject({ active: false, wins: 1, matchPoints: 1 });
  await second.goto(`/t/${id}?browse=1#standings`);
  await capture(second, "19-final-standings", info.project.name);
  await second.goto(`/t/${id}/players/${departed}`);
  await capture(second, "20-retained-player-history", info.project.name);
  writeEvidence(`tables-${info.project.name}.json`, { id, departed, snapshot: current, savedTime: saved.state?.usedMs, oldDeviceRejected: true });
  await secondContext.close();
});

test("TABLES: external result drafts, explicit login return, idle movement and release", async ({ page }, info) => {
  await login(page);
  const id = await createSimpleTournament(page, "Club night", "Alex Rowan\nMorgan Vale", 1, 2, 10, null);
  await page.goto(`/admin/tournaments/${id}/tables`);
  await page.getByLabel("Table numbers", { exact: true }).fill("1, 2");
  await page.getByRole("button", { name: "Enable table management", exact: true }).click();
  await page.getByRole("button", { name: "Use this device at Table 1", exact: true }).click();
  await page.getByLabel("Assign to table", { exact: true }).selectOption("2");
  await page.getByRole("button", { name: "Change this device's table", exact: true }).click();
  await expect(page.getByText("This device serves Table 2.", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Remove this device from table duty", exact: true }).click();
  await expect(page.getByText("Removed from table duty. Organizer sign-in remains active.", { exact: true })).toBeVisible();
  await page.getByLabel("Assign to table", { exact: true }).selectOption("1");
  await page.getByRole("button", { name: "Use this device at Table 1", exact: true }).click();
  const current = await publishNext(page, id, 1);
  const match = current.rounds[0].matches[0];
  await page.goto(`/t/${id}/table`);
  const card = page.locator(`#match-${match.id}`);
  await card.getByRole("button", { name: "Report result", exact: true }).click();
  await fillScore(card, 401, 399, 20, 0);
  await page.reload();
  await card.getByRole("button", { name: "Report result", exact: true }).click();
  await card.getByRole("button", { name: "Restore draft", exact: true }).click();
  await expect(card.getByLabel("Score", { exact: true }).nth(0)).toHaveValue("401");
  await expect(card.getByLabel("Overtime (m:ss)", { exact: true }).nth(0)).toHaveValue("0:20");
  await capture(page, "21-manual-report-draft", info.project.name);
  await card.getByRole("button", { name: "Save result", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Result saved · Round 1", exact: true })).toBeVisible();
  await capture(page, "22-waiting-after-manual-result", info.project.name);
  expect((await snapshot(page.request, id)).rounds[0].matches[0].result).toMatchObject({ adjusted1: 397, adjusted2: 399 });
  await page.request.delete(`${baseURL}/api/auth`, { headers: { Origin: baseURL } });
  await page.goto(`/t/${id}/table`);
  await page.getByRole("link", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/login\?next=/);
  expect(new URL(page.url()).searchParams.get("next")).toBe(`/t/${id}/table`);
  await capture(page, "23-sign-in-return", info.project.name);
  // Reuse the existing fixture without leaking its credentials into evidence.
  const { readFileSync } = await import("node:fs");
  const auth = JSON.parse(readFileSync(process.env.CROSSPLAY_E2E_AUTH_FIXTURE!, "utf8"));
  await page.getByLabel("Email", { exact: true }).fill(auth.email);
  await page.getByLabel("Password", { exact: true }).fill(auth.password);
  await page.getByRole("button", { name: "Sign in", exact: true }).click();
  await expect(page).toHaveURL(/\/table$/);
  await expect(page.getByRole("heading", { name: "Table 1", exact: true })).toBeVisible();
});
